 export const BankList = [
    { label: "Allahabad Bank" },
    { label: "Andhra Bank" },
    { label: "AXIS Bank" },
    { label: "Bank of Bahrain &amp; Kuwait" },
    { label: "Bank of Baroda" },
    { label: "Bank of Maharashtra" },
    { label: "Bank of Rajasthan" },
    { label: "Bank Of India" },
    { label: "Central Bank of India" },
    { label: "Centurion Bank of Punjab" },
    { label: "City Union Bank" },
    { label: "Corporation Bank" },
    { label: "Deutsche Bank" },
    { label: "Development Credit Bank" },
    { label: "Dhanlaxmi Bank" },
    { label: "Federal Bank" },
    { label: "HDFC Bank" },
    { label: "ICICI Bank" },
    { label: "IDBI Bank" },
    { label: "Indian Bank" },
    { label: "Indian Overseas Bank" },
    { label: "IndusInd Bank" },
    { label: "ING Vysya bank" },
    { label: "Jammu And Kashmir Bank" },
    { label: "Karnataka Bank" },
    { label: "Karur Vyasa Bank" },
    { label: "Kotak Mahindra Bank" },
    { label: "Lakshmi Vilas Bank" },
    { label: "Oriental Bank of Commerce" },
    { label: "Punjab and Sind Bank" },
    { label: "Punjab National Bank " },
    { label: "Shamrao Vitthal Co-operative Bank" },
    { label: "South Indian Bank" },
    { label: "Standard Chartered Bank" },
    { label: "State Bank of Bikaner and Jaipur" },
    { label: "State Bank of Hyderabad" },
    { label: "State Bank of India" },
    { label: "State Bank of MYSORE" },
    { label: "State Bank of Patiala" },
    { label: "State Bank of Travancore" },
    { label: "Syndicate Bank" },
    { label: "Tamilnad Mercantile Bank" },
    { label: "The Royal Bank of Scotland N.V." },
    { label: "Union Bank of India Debit Card" },
    { label: "Union Bank Of India" },
    { label: "United Commercial Bank" },
    { label: "Vijaya Bank" },
    { label: "YES Bank" },
    { label: "Any Other" },
  ];

  export const MonthsList = [
    { label: "January", value: 1 },
    { label: "February", value: 2 },
    { label: "March", value: 3 },
    { label: "April", value: 4 },
    { label: "May", value: 5 },
    { label: "June", value: 6 },
    { label: "July", value: 7 },
    { label: "August", value: 8 },
    { label: "September", value: 9 },
    { label: "October", value: 10 },
    { label: "November", value: 11 },
    { label: "December", value: 12 },
  ];